jobs:
  build:
    name: Create Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4.1.7
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create Release
      uses: actions/create-release@v1.1.4
      with:
        draft: true
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
name: Create Release from semantic versioning tag push
on:
  repository_dispatch:
    types: trigger-ga___create_github_release.yml
