concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  checkstyle_check:
    name: Validate checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout latest code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Validate Project Checkstyle
      run: ./mvnw -B checkstyle:check
  maven_test:
    env:
      JDK: ${{ matrix.jdk }}
      OS: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout latest code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-package: jdk
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Echo exact java version being used
      run: java -version
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Test with Maven (incl. slow tests)
      run: ./mvnw -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -B --errors clean test --activate-profiles AlsoSlowTests
      shell: bash
    - continue-on-error: true
      name: CodeCov - JavaParser Core
      timeout-minutes: 10
      uses: codecov/codecov-action@v4.5.0
      with:
        env_vars: OS,JDK
        fail_ci_if_error: false
        files: javaparser-core-testing/target/site/jacoco/jacoco.xml,javaparser-core-testing-bdd/target/site/jacoco/jacoco.xml
        flags: javaparser-core,AlsoSlowTests,${{ matrix.os }},jdk-${{ matrix.jdk }}
        verbose: false
    - continue-on-error: true
      name: CodeCov - JavaParser Symbol Solver
      timeout-minutes: 10
      uses: codecov/codecov-action@v4.5.0
      with:
        env_vars: OS,JDK
        fail_ci_if_error: false
        file: javaparser-symbol-solver-testing/target/site/jacoco/jacoco.xml
        flags: javaparser-symbol-solver,AlsoSlowTests,${{ matrix.os }},jdk-${{ matrix.jdk
          }}
        verbose: false
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
  spotless_check:
    name: Validate code generation and formatting
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout latest code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Generate code and format
      run: './run_core_metamodel_generator.sh

        # ./run_core_generators.sh automatically runs ./mvnw spotless:apply

        ./run_core_generators.sh

        git diff --exit-code

        '
name: Build and test (using maven)
on:
  repository_dispatch:
    types: trigger-ga___maven_tests.yml
