jobs:
  generate_changelog:
    name: Generate Changelog
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v4.1.7
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      id: vars
      name: Generate Changelog
      run: '## By convention, the "next" milestone is named "next release"

        ./run_generate_changelog_by_milestone_title.sh "next release"


        SHA_LONG=$(git rev-parse HEAD)

        SHA_SHORT=$(git rev-parse --short HEAD)

        CHANGELOG="$(<temp_changelog.md)"

        RELEASE_TITLE="SNAPSHOT - $SHA_SHORT"

        RELEASE_TAG_NAME="v_snapshot_$SHA_SHORT"


        echo "sha_long=$SHA_LONG" >> $GITHUB_OUTPUT

        echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT

        echo "changelog<<EOF" >> $GITHUB_OUTPUT

        echo "$CHANGELOG" >> $GITHUB_OUTPUT

        echo "EOF" >> $GITHUB_OUTPUT

        echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT

        echo "release_tag_name=$RELEASE_TAG_NAME" >> $GITHUB_OUTPUT

        '
      shell: bash
      working-directory: ./scripts
    - continue-on-error: true
      name: Output variables
      run: 'echo sha_short = ${{ steps.vars.outputs.sha_short }}

        echo sha_long  = ${{ steps.vars.outputs.sha_long }}

        echo changelog = "${{ steps.vars.outputs.changelog }}"

        echo changelog = "${{ steps.vars.outputs.release_title }}"

        echo changelog = "${{ steps.vars.outputs.release_tag_name }}"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Remove Old Release Drafts
      run: "gh api repos/{owner}/{repo}/releases \\\n  --jq '.[] | select(.draft ==\
        \ true) | .id' \\\n  | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create Release Draft
      run: "gh release create ${{ steps.vars.outputs.release_tag_name }}  \\\n  --target\
        \ ${{ steps.vars.outputs.sha_long }} \\\n  --draft \\\n  --prerelease \\\n\
        \  --title \"${{ steps.vars.outputs.release_title }}\" \\\n  --notes-file\
        \ ./scripts/temp_changelog.md\n"
name: Build Snapshot
on:
  repository_dispatch:
    types: trigger-ga___prepare_release_changelog.yml
